// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_EmpresaBus_API.Data;

#nullable disable

namespace Proyecto_EmpresaBus_API.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsientoID"), 1L, 1);

                    b.Property<int>("AutobusID")
                        .HasColumnType("int");

                    b.Property<int>("NumeroAsiento")
                        .HasColumnType("int");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AsientoID");

                    b.HasIndex("AutobusID", "NumeroAsiento")
                        .IsUnique();

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Autobus", b =>
                {
                    b.Property<int>("AutobusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutobusID"), 1L, 1);

                    b.Property<int>("CapacidadTotal")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroBus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutobusID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Autobuses");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Boleto", b =>
                {
                    b.Property<int>("BoletoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoletoID"), 1L, 1);

                    b.Property<int>("AsientoID")
                        .HasColumnType("int");

                    b.Property<string>("EstadoBoleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("ViajeID")
                        .HasColumnType("int");

                    b.HasKey("BoletoID");

                    b.HasIndex("AsientoID");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("ViajeID", "AsientoID")
                        .IsUnique()
                        .HasFilter("[EstadoBoleto] = 'Confirmado'");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Empresa", b =>
                {
                    b.Property<int>("EmpresaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaID"), 1L, 1);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpresaID");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Localidad", b =>
                {
                    b.Property<int>("LocalidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalidadID"), 1L, 1);

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NombreLocalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinciaID")
                        .HasColumnType("int");

                    b.HasKey("LocalidadID");

                    b.HasIndex("ProvinciaID");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Parada", b =>
                {
                    b.Property<int>("ParadaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParadaID"), 1L, 1);

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NombreParada")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ParadaID");

                    b.HasIndex("LocalidadID");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Provincia", b =>
                {
                    b.Property<int>("ProvinciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinciaID"), 1L, 1);

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProvinciaID");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Ruta", b =>
                {
                    b.Property<int>("RutaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutaID"), 1L, 1);

                    b.Property<int>("DestinoID")
                        .HasColumnType("int");

                    b.Property<decimal>("DistanciaKM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreRuta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrigenID")
                        .HasColumnType("int");

                    b.HasKey("RutaID");

                    b.HasIndex("DestinoID");

                    b.HasIndex("OrigenID");

                    b.ToTable("Rutas");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.RutaParada", b =>
                {
                    b.Property<int>("RutaID")
                        .HasColumnType("int");

                    b.Property<int>("ParadaID")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("RutaID", "ParadaID");

                    b.HasIndex("ParadaID");

                    b.ToTable("RutaParadas");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"), 1L, 1);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LocalidadID")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LocalidadID");

                    b.HasIndex("Telefono")
                        .IsUnique()
                        .HasFilter("[Telefono] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Viaje", b =>
                {
                    b.Property<int>("ViajeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViajeID"), 1L, 1);

                    b.Property<int>("AutobusID")
                        .HasColumnType("int");

                    b.Property<string>("EstadoViaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaLlegadaEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("NumeroServicio")
                        .HasColumnType("int");

                    b.Property<string>("Plataforma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RutaID")
                        .HasColumnType("int");

                    b.HasKey("ViajeID");

                    b.HasIndex("AutobusID");

                    b.HasIndex("RutaID");

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Asiento", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Autobus", "Autobus")
                        .WithMany("Asientos")
                        .HasForeignKey("AutobusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autobus");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Autobus", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Boleto", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Asiento", "Asiento")
                        .WithMany()
                        .HasForeignKey("AsientoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EmpresaBus_API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EmpresaBus_API.Models.Viaje", "Viaje")
                        .WithMany("Boletos")
                        .HasForeignKey("ViajeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Usuario");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Localidad", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Parada", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Ruta", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Localidad", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_EmpresaBus_API.Models.Localidad", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.RutaParada", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Parada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EmpresaBus_API.Models.Ruta", "Ruta")
                        .WithMany("RutaParadas")
                        .HasForeignKey("RutaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parada");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Usuario", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadID");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Viaje", b =>
                {
                    b.HasOne("Proyecto_EmpresaBus_API.Models.Autobus", "Autobus")
                        .WithMany("Viajes")
                        .HasForeignKey("AutobusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EmpresaBus_API.Models.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autobus");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Autobus", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Ruta", b =>
                {
                    b.Navigation("RutaParadas");
                });

            modelBuilder.Entity("Proyecto_EmpresaBus_API.Models.Viaje", b =>
                {
                    b.Navigation("Boletos");
                });
#pragma warning restore 612, 618
        }
    }
}
